version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - .env  
    container_name: k8s-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID={AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    depends_on:
      - mongo
    volumes:
      - ./backend/key.pem:/app/key.pem
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile   # ✅ production Dockerfile (nginx)
    container_name: k8s-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:7
    container_name: k8s-mongo
    ports:
      - "27017:27017"
    restart: always
