version: "3.9"

services:
  backend:
    build: ./backend
    container_name: k8s-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./backend/key.pem:/app/key.pem

  frontend:
    build: ./frontend
    container_name: k8s-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: k8s-mongo
    ports:
      - "27017:27017"
